name: Windows

on: [push, pull_request]

defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    name: ${{matrix.sys}}-${{matrix.env}}-${{matrix.build_type}}
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        build_type: [Release, Debug]
        sys: [mingw32, mingw64]
        include:
          - sys: mingw32
            env: i686
          - sys: mingw64
            env: x86_64

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      if: ${{ startswith(matrix.sys, 'mingw') }}
      with:
        msystem: ${{matrix.sys}}
        install: >-
          mingw-w64-${{matrix.env}}-boost
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-gcc
          mingw-w64-${{matrix.env}}-ninja

    - name: Configure
      if: ${{ startswith(matrix.sys, 'mingw') }}
      env:
        CXX: ${{matrix.env}}-w64-mingw32-g++
      run: |
        cmake -S . -B build_${{matrix.build_type}}/ -G Ninja

    - name: Build
      if: ${{ startswith(matrix.sys, 'mingw') }}
      run: |
        cmake --build build_${{matrix.build_type}}/ --config ${{matrix.build_type}}

    - name: Run tests
      run: |
        ctest --test-dir build_${{matrix.build_type}} --config ${{matrix.build_type}}
